### ISSUE TITLE
Does not work after reboot/sleep/etc.

### ISSUE THREAD

**Issue by Ciantic** [Ciantic/monitortoggler#2]
If the AdapterID changes, the restoring from file does not work anymore.

This happens somewhat often on my computer, e.g. during computer reboot, sleep and wakeup. For the time being I'd like to advice _not use_ restoremonitors7. I have no time to improve on this program at the very moment.

**Alexey Grigoriev** managed to fix this by:

> I've resolved the problem by getting current AdapterID and replacing the AdapterID which is read from file by current id in the source code.

**Comment by rbresalier** [comment]
I fixed this issue in my fork and issued a pull request: https://github.com/Ciantic/monitortoggler/pull/3

**Comment by Ciantic** [comment]
Great work! I have zero need for this tool at the moment. Happily accept this PR.
